# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
  secret_key:      '%env(resolve:JWT_SECRET_KEY)%'
  public_key:      '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase:     '%env(JWT_PASSPHRASE)%'
  token_ttl:       3600 # 1 hora

  # Opcional: usa el email como claim de identificación
  user_id_claim:   'email'

  token_extractors:
    authorization_header:
      enabled: true
      prefix: 'Bearer'
    cookie:
      enabled: false
      # name: 'BEARER'
    query_parameter:
      enabled: false
      # name: 'bearer'
    split_cookie:
      enabled: false
      # prefix: 'BEARER='
