security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Usuario
        property: email
    users_in_memory: { memory: null }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: users_in_memory

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    # 1) Auth API (anon)
    - { path: ^/api/auth/registrar$,      roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
    - { path: ^/api/auth/login$,          roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
    - { path: ^/api/auth/refresh-token$,  roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }

    # 2) Usuarios API (solo ADMIN puede CRUD)
    - { path: ^/api/usuarios,              roles: ROLE_ADMIN }

    # 3) Categorías, Tareas y Reportes API (cualquier USER logueado)
    - { path: ^/api/categorias,            roles: ROLE_USER }
    - { path: ^/api/tareas,                roles: ROLE_USER }
    - { path: ^/api/reportes,              roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10




