security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Usuario
        property: email
    users_in_memory: { memory: null }

  firewalls:
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

    refresh_token:
      pattern: ^/api/auth/refresh-token
      stateless: true
      provider: app_user_provider

  access_control:

    # 1) Usuarios API (solo ADMIN puede CRUD)
    - { path: ^/api/usuarios,              roles: ROLE_ADMIN }

    # 2) Categorías, Tareas y Reportes API (cualquier USER logueado)
    - { path: ^/api/categorias,            roles: ROLE_USER }
    - { path: ^/api/tareas,                roles: ROLE_USER }
    - { path: ^/api/reportes,              roles: ROLE_USER }

    # 3) refrescar token sin autorización. 
    - { path: ^/api/auth/refresh-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10




